default: &default
  adapter: <%= ENV["db_adapter"] %>
  timeout: 5000
  pool: <%= ENV["db_pool"] %>
  host: <%= ENV["db_host"] %>
  database: <%= ENV["db_name"] %>
  username: <%= ENV["db_user"] %>
  password: <%= ENV["db_pass"] %>

development:
  <<: *default
test:
  <<: *default
production:
  <<: *default
